default: &default
  adapter: mysql2
  encoding: utf8

development:
  <<: *default
  database: my_store_development
  pool: 5
  username: root
  password:
  host: localhost
  port: 3306

test: &test
  <<: *default
  database: my_store_test
  pool: 5
  username: root
  password:
  host: localhost
  port: 3306